import assert from "node:assert/strict";
import fs from "node:fs";
import path from "node:path";
import test from "node:test";

const root = path.resolve(import.meta.dirname, "..");
const rust = fs.readFileSync(path.join(root, "src-tauri", "src", "lib.rs"), "utf8");
const frontend = fs.readFileSync(path.join(root, "src", "main.ts"), "utf8");

test("IPC commands validate structured requests and launch only the fixed Python backend", () => {
  assert.match(rust, /fn shell_readiness\(\) -> ShellReadiness/);
  assert.match(rust, /fn doctor_report\(\) -> Result<serde_json::Value, String>/);
  assert.match(rust, /fn preflight_source\(path: String\) -> Result<SourcePreflight, String>/);
  assert.match(rust, /symlink_metadata\(candidate\)/);
  assert.match(rust, /metadata\.file_type\(\)\.is_symlink\(\)/);
  assert.match(rust, /"mp3", "m4a", "wav", "flac", "mp4", "mkv", "mov", "webm"/);
  assert.match(rust, /struct StartJobRequest/);
  assert.match(rust, /struct StartSetupRequest/);
  assert.match(rust, /fn start_job\(app: AppHandle, request: StartJobRequest\)/);
  assert.match(rust, /fn start_setup\(request: StartSetupRequest\)/);
  assert.match(rust, /fn cancel_job\(operation_id: String\)/);
  assert.match(rust, /"summary" \| "introduction" \| "both"/);
  assert.match(rust, /"--progress-format"/);
  assert.match(rust, /"--qwen-model"/);
  assert.match(rust, /DEFAULT_QWEN_MODEL/);
  assert.match(rust, /qwen3\.6:35b-a3b-agent-64k/);
  assert.match(rust, /job_result/);
  assert.match(rust, /job_failed/);
  assert.match(rust, /job_cancelled/);
  assert.match(rust, /MAX_STDERR_LINES/);
  assert.match(rust, /MAX_STDERR_CHARS/);
  assert.match(rust, /sanitize_stderr_line/);
  assert.match(rust, /classify_stderr_tail/);
  assert.match(rust, /valid_backend_report/);
  assert.match(rust, /"category": category/);
  assert.match(rust, /let backend_connected = script_ready && python_ready/);
  assert.match(rust, /generate_handler!\[[\s\S]*start_job[\s\S]*start_setup[\s\S]*cancel_job/);
  assert.match(rust, /shell_version:/);
  assert.match(rust, /message:/);
  assert.match(rust, /Command::new/);
  assert.doesNotMatch(rust, /Command::new\(["']cmd["']/i);
  assert.doesNotMatch(rust, /Command::new\(["']powershell["']/i);
  assert.match(frontend, /invoke<ShellReadiness>\("shell_readiness"\)/);
  assert.match(frontend, /invoke<DoctorReport>\("doctor_report"\)/);
  assert.match(frontend, /invoke<\{ file_name: string; byte_length: number \}>\("preflight_source", \{ path: selectedSourcePath \}\)/);
  assert.match(frontend, /doctorReadiness\.textContent/);
  assert.match(rust, /tauri_plugin_dialog::init\(\)/);
  assert.match(frontend, /sourceButton\.addEventListener\("click"/);
  assert.match(frontend, /open\(\{[\s\S]*multiple: false[\s\S]*directory: false/);
  assert.match(frontend, /value\.split\(\/\[\\\\\/\]\//);
  assert.match(frontend, /invoke<\{ operation_id: string \}>\("start_job"/);
  assert.match(frontend, /invoke\("cancel_job"/);
  assert.match(frontend, /listen<BackendProgressEvent>\("progress"/);
  assert.match(frontend, /listen<\{ operation_id: string; report: JobReport \}>\("job_result"/);
  assert.match(frontend, /listen<\{ operation_id: string; error\?:/);
  assert.match(frontend, /listen<\{ operation_id: string \}>\("job_cancelled"/);
  assert.match(frontend, /readiness\.textContent/);
});
